### ISSUE TITLE
[UI ISSUES] - Minor

### ISSUE THREAD

**Issue by xyizko** [solodit/feedback#51]
![](https://i.postimg.cc/JhspJzRT/image.png)

----

![](https://i.postimg.cc/Dw9Xjvqp/image.png)

---

OS: Debian 12 x64
Browser: Firefox

**Comment by xyizko** [comment]
Suggested Fix alter dimensions in this line , in the source, in this line `class`

```html 
<img src="https://solodit-bucket.s3.amazonaws.com/storage/images/af_logos/images.jpg" class="mx-3 w-32 rounded" alt="Immunefi">
```

**Comment by wang6131** [comment]
Thank you for your report.
We solved this issue.
